### ISSUE TITLE
2008-2012 PUMS

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#10]
Hey @AmandaDoyle I have a question about the "2008-2012 PUMS" source in the field specifications page of the [data matrix on sharepoint](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/_layouts/15/Doc.aspx?sourcedoc=%7BBCF3241D-23FC-491A-8C83-B99A504076B9%7D&file=Intro%201572-B%20data%20matrix%20-%20Current.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1) 
Does this refer to the PUMS 5-year estimates ending in 2012? So where the 2015-2019 PUMS is downloaded [here](https://data.census.gov/mdat/#/search?ds=ACSPUMS5Y2019) the 2008-2012 PUMS is downloaded [here](https://data.census.gov/mdat/#/search?ds=ACSPUMS5Y2012).

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  Yes, exactly.

**Comment by SashaWeinstein** [comment]
awesome thanks

**Comment by SashaWeinstein** [comment]
reopening this issue as @mbh329 has been working on it for some time. @mbh329 if there is already issue for this that I missed let me know

**Comment by mbh329** [comment]
The 2008-2012 5 Year ACS estimates are different than other 5 year ACS estimates because they include  "two sets of PUMA geographies on this file, which is different from all previously published ACS PUMS files. The 2008-2012 ACS PUMS files use PUMA boundaries that were drawn by state governments at the time of Census 2000 and the 2010 Census" (ACS). The 2008-2012 data has PUMA level geography but within the data itself as columns for both 2000 and 2010 PUMA geo's. After looking at the differences between NYC PUMA geography, we determined that there are no substantial changes - marginal movement in PUMA borders (see resources section for map) - although moving forward to will need to think about how the 2020 PUMA redraw will impact our unit of analysis. 

For the 2008-2012 ACS 5-year estimates, I see 3 ways forward:

1. The most simple solution (based on the current ETL used for the 2015-1019 ACS) would be to use the 2007-2011 5 Year ACS because of the way that the MDAT census API query works. Requires a simple addition to ETL script @SashaWeinstein wrote by just adding the 2011 year 

- [ ] Double check the 2011 year query works as expected
- [ ] Will have to check with SME's if this works for them 
- [ ] Talk with Lynn and Amanda 


2. After speaking with the Census, they mentioned that the PUMA level geography does exist but as columns in the data tables (unlike the 2015 0219 ACS). We are doing some testing as to whether this works well and if there are any records with different PUMA's in 2000 and 2010 that would be problematic for any analysis/ETL work. 

- [ ] Check to see if there are any records with different PUMA's
- [ ] How easy is it to query the API and extract the data so it aligns with data tables from the 2015-19 ACS?

3. Erica Mauer (DCP Population), mentioned that we could use IPUMS to query the ACS data but this would require redoing the ETL code that has already been written and would require some retooling of certain indicators on the spreadsheet (different codes in the IPUMS data vs census). IPUMS data is different than census data: "The IPUMS data harmonizes variables as closely as possible with previous data releases; this often results in new variable names, codes, and labels. Variables reporting dollar values have been pre-standardized to constant dollars; original PUMS values are not adjusted, and users must apply the Census Bureau-provided adjustment factor manually" (IPUMS). 


Resources:

**ACS**

Census MDAT GUI
[https://data.census.gov/mdat/#/](url)

2008-2012 ACS 5 Year Data Documentation 
[https://www2.census.gov/programs-surveys/acs/tech_docs/pums/ACS2008_2012_PUMS_README.pdf](url)

**IPUMS**

ACS 5 year documentation 
[https://usa.ipums.org/usa/acs_multyr.shtml ](url)

IPUMS Developer Portal
[https://developer.ipums.org/docs/get-started/](url)

**Comment by mbh329** [comment]
@AmandaDoyle and @SashaWeinstein feel free to edit/add as we move forward

**Comment by SashaWeinstein** [comment]
Great comment! This is super helpful. I started working on option 2 friday afternoon. My work is in [this notebook](https://github.com/NYCPlanning/db-equitable-development-tool/blob/10-2012-PUMS-Exploratory/2012_5YearEstimates_PUMA_Column.ipynb).  Curious about your thoughts @mbh329.

I don't know if is possible to track records to see if their PUMAs change from one survey to the next. People get unique identifiers within the survey they participate in but if the census tracks particular people from year to year I don't know where that data lives

**Comment by SashaWeinstein** [comment]
Next steps:
Amanda: Find source on BYTES of big apple to sanity check against?
Max: compare more PUMAs. 

We needed to multiply by weights, these should match PUMA estimates for population. We need to find some source on populations by PUMA to see if we get correct answer.
