### ISSUE TITLE
Update source data and logic for creating units_rad in Housing Security and Quality

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#265]
**units_rad**
Comes `All Counted Units` field in [Housing New York Units by Building](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.cityofnewyork.us%2FHousing-Development%2FHousing-New-York-Units-by-Building%2Fhg8x-zxpr&data=04%7C01%7CADoyle%40planning.nyc.gov%7C588d4551596244e1cd3508da1411fa0b%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C637844364683915760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DFwZMgsLap8VYQYwAHf1oGw0LpThDVJo%2BVhakp3FPJw%3D&reserved=0)
We have logic to assign PUMA and Borough for each record.  SUM `All Counted Units` by each geographic level.

**Comment by mbh329** [comment]
@levysamu I don't quite understand why we are using the housing new york dataset to get` units_rad.` I thought the housing new york dataset documents the total number of affordable units that HPD is responsible for while RAD units relates to the specific number of nycha units that have gone through the federally backed RAD conversion program

**Comment by levysamu** [comment]
We are not using HNY for RAD units. We aren't using RAD units at all for anything.

The problem now is that there are two fields in the Income Restricted Units table shown below, but the bottom one is pulling the wrong information. Units With Regulatory Agreements Since 2014 is currently displaying RAD units when it should be showing HNY units. We don't need to display RAD units anywhere in the EDDE. We need all NYCHA units (of which RAD is a subset) and all HNY units.

![image](https://user-images.githubusercontent.com/17015121/161343928-e5260ff7-1c03-455b-8d23-851861bd586d.png)

**Comment by mbh329** [comment]
Okay, great. I think that issue was lost in translation but it is clear now

**Comment by AmandaDoyle** [comment]
@mbh329 The logic for filtering and assigning records to a geographic area should be the same as [this indicator](https://github.com/NYCPlanning/db-equitable-development-tool/issues/30) as source data is the same.
Therefore:
1) Do not filter out confidential projects
2) If the project has borough information include the records at the Brough or Citywide level
